version: '3'

services:
# Only for local installation

  pg:
    container_name: pg
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=tgbot
      - POSTGRES_DB=tgbot
    ports:
     - 5432:5432
    restart: always

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
     - 5672:5672
     - 15672:15672
    restart: always

  tgbot:
    container_name: tgbot
    build: .
    depends_on:
      - rabbit
      - pg
    restart: always

  mongo:
    image: mongo:4.4.14
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tgbot
      - MONGO_INITDB_ROOT_PASSWORD=tgbot
