postgres:
  database_url:
  require_ssl: false

rabbit:
  cloudamqp:
  require_ssl: false
  queue_name: tgbot_updates
  capacity: 5

mongo:
  mongo_url:

s3:
  service_name: s3
  bucket_name: plotsbucket

telegram:
  bot_token: