postgres:
  database_url: $DATABASE_URL
  require_ssl: false

rabbit:
  cloudamqp: $CLOUDAMQP
  require_ssl: false
  queue_name: tgbot_updates
  capacity: 5

mongo:
  mongo_url: $MONGO_URL

s3:
  service_name: s3
  bucket_name: $AWS_BUCKET_NAME

telegram:
  bot_token: $BOT_TOKEN